// This is code generated from the database.json by card_enum_generator.rs. Do not edit manually.

use std::collections::HashSet;
use std::sync::LazyLock;

// Type aliases matching those in actions::apply_action_helpers
pub type Probabilities = Vec<f64>;
pub type Mutations = Vec<Box<dyn FnOnce(&mut rand::rngs::StdRng, &mut crate::State, &crate::actions::Action)>>;
pub type AttackEffect = Option<(Probabilities, Mutations)>;

static KNOWN_EFFECTS: LazyLock<HashSet<&'static str>> = LazyLock::new(|| {
    let mut set = HashSet::new();
    set.insert("Heal 30 damage from this Pokémon.");
    set.insert("Put 1 random [G] Pokémon from your deck into your hand.");
    set.insert("Your opponent's Active Pokémon is now Asleep.");
    set.insert("Your opponent's Active Pokémon is now Poisoned.");
    set.insert("Flip a coin. If heads, this attack does 30 more damage.");
    set.insert("Flip a coin. If heads, this attack does 40 more damage.");
    set.insert("Heal 10 damage from this Pokémon.");
    set.insert("Flip 2 coins. This attack does 50 damage for each heads.");
    set.insert("Take a [G] Energy from your Energy Zone and attach it to 1 of your Benched [G] Pokémon.");
    set.insert("Flip a coin. If tails, this attack does nothing.");
    set.insert("Discard a [R] Energy from this Pokémon.");
    set.insert("Discard 2 [R] Energy from this Pokémon.");
    set.insert("Flip a coin. If heads, the Defending Pokémon can't attack during your opponent's next turn.");
    set.insert("This Pokémon also does 20 damage to itself.");
    set.insert("Flip 3 coins. Take an amount of [R] Energy from your Energy Zone equal to the number of heads and attach it to your Benched [R] Pokémon in any way you like.");
    set.insert("If this Pokémon has at least 2 extra [W] Energy attached, this attack does 60 more damage.");
    set.insert("Your opponent can't use any Supporter cards from their hand during their next turn.");
    set.insert("Flip 2 coins. If both of them are heads, this attack does 80 more damage.");
    set.insert("This attack does 50 damage to 1 of your opponent's Pokémon.");
    set.insert("Discard a random Energy from your opponent's Active Pokémon.");
    set.insert("If this Pokémon has at least 3 extra [W] Energy attached, this attack does 70 more damage.");
    set.insert("During your opponent's next turn, the Defending Pokémon can't attack.");
    set.insert("Flip a coin. If heads, your opponent's Active Pokémon is now Paralyzed.");
    set.insert("This attack also does 10 damage to each of your opponent's Benched Pokémon.");
    set.insert("If your opponent's Active Pokémon has damage on it, this attack does 60 more damage.");
    set.insert("Discard all Energy from this Pokémon.");
    set.insert("This attack does 30 damage for each of your Benched [L] Pokémon.");
    set.insert("Flip a coin. If heads, this attack does 40 more damage. If tails, this Pokémon also does 20 damage to itself.");
    set.insert("Flip 4 coins. This attack does 40 damage for each heads.");
    set.insert("This attack also does 30 damage to 1 of your Benched Pokémon.");
    set.insert("Flip 4 coins. This attack does 50 damage for each heads.");
    set.insert("This attack does 30 damage to 1 of your opponent's Pokémon.");
    set.insert("Switch this Pokémon with 1 of your Benched Pokémon.");
    set.insert("This attack does 30 more damage for each Energy attached to your opponent's Active Pokémon.");
    set.insert("During your opponent's next turn, this Pokémon takes -20 damage from attacks.");
    set.insert("This attack does 20 more damage for each Energy attached to your opponent's Active Pokémon.");
    set.insert("Discard 2 [P] Energy from this Pokémon.");
    set.insert("Flip 2 coins. This attack does 100 damage for each heads.");
    set.insert("Flip a coin. If heads, during your opponent's next turn, prevent all damage from—and effects of—attacks done to this Pokémon.");
    set.insert("If this Pokémon has damage on it, this attack does 60 more damage.");
    set.insert("This Pokémon also does 50 damage to itself.");
    set.insert("During your opponent's next turn, attacks used by the Defending Pokémon do -20 damage.");
    set.insert("Flip 2 coins. This attack does 80 damage for each heads.");
    set.insert("This attack does 30 damage to 1 of your opponent's Benched Pokémon.");
    set.insert("Heal from this Pokémon the same amount of damage you did to your opponent's Active Pokémon.");
    set.insert("Switch out your opponent's Active Pokémon to the Bench. (Your opponent chooses the new Active Pokémon.)");
    set.insert("During your opponent's next turn, the Defending Pokémon can't retreat.");
    set.insert("Put 1 random Nidoran♂ from your deck onto your Bench.");
    set.insert("This attack does 50 more damage for each of your Benched Nidoking.");
    set.insert("If your opponent's Active Pokémon is Poisoned, this attack does 50 more damage.");
    set.insert("Flip a coin. If heads, discard a random Energy from your opponent's Active Pokémon.");
    set.insert("Take a [M] Energy from your Energy Zone and attach it to this Pokémon.");
    set.insert("1 of your opponent's Pokémon is chosen at random 4 times. For each time a Pokémon was chosen, do 50 damage to it.");
    set.insert("Draw a card.");
    set.insert("Flip a coin. If heads, discard a random card from your opponent's hand.");
    set.insert("Flip a coin until you get tails. This attack does 60 damage for each heads.");
    set.insert("Flip 2 coins. This attack does 30 damage for each heads.");
    set.insert("Choose 1 of your opponent's Pokémon's attacks and use it as this attack. If this Pokémon doesn't have the necessary Energy to use that attack, this attack does nothing.");
    set.insert("Flip a coin. If heads, your opponent shuffles their Active Pokémon into their deck.");
    set.insert("This attack does 30 damage for each of your Benched Pokémon.");
    set.insert("Your opponent reveals their hand.");
    set.insert("Take a [G] Energy from your Energy Zone and attach it to this Pokémon.");
    set.insert("Flip a coin for each Energy attached to this Pokémon. This attack does 50 damage for each heads.");
    set.insert("If this Pokémon has at least 3 extra [G] Energy attached, this attack does 70 more damage.");
    set.insert("Flip a coin. If heads, this attack does 60 more damage.");
    set.insert("Discard 2 [R] Energy from this Pokémon. This attack does 80 damage to 1 of your opponent's Pokémon.");
    set.insert("If your opponent's Active Pokémon is Poisoned, this attack does 40 more damage.");
    set.insert("Discard a random Energy from among the Energy attached to all Pokémon (both yours and your opponent's).");
    set.insert("This attack does 50 damage to 1 of your opponent's Benched Pokémon.");
    set.insert("This attack does 10 damage for each of your Benched [L] Pokémon.");
    set.insert("This attack also does 20 damage to each of your opponent's Benched Pokémon.");
    set.insert("This attack does 40 damage to 1 of your opponent's Pokémon.");
    set.insert("Choose 1 of your opponent's Active Pokémon's attacks and use it as this attack.");
    set.insert("This attack does 20 more damage for each of your opponent's Benched Pokémon.");
    set.insert("Heal 20 damage from each of your Pokémon.");
    set.insert("During your opponent's next turn, this Pokémon takes -30 damage from attacks.");
    set.insert("If any of your Pokémon were Knocked Out by damage from an attack during your opponent's last turn, this attack does 60 more damage.");
    set.insert("Put 1 random Koffing from your deck onto your Bench.");
    set.insert("During your opponent's next turn, if the Defending Pokémon tries to use an attack, your opponent flips a coin. If tails, that attack doesn't happen.");
    set.insert("If your opponent's Active Pokémon is a Pokémon ex, this attack does 80 more damage.");
    set.insert("Flip a coin until you get tails. This attack does 20 damage for each heads.");
    set.insert("Shuffle your hand into your deck. Draw a card for each card in your opponent's hand.");
    set.insert("Discard a random Energy from this Pokémon.");
    set.insert("During your next turn, this Pokémon can't use Frenzy Plant.");
    set.insert("Your opponent's Active Pokémon is now Confused.");
    set.insert("Put 1 random Basic Pokémon from your deck onto your Bench.");
    set.insert("Flip a coin. If heads, this attack does 50 more damage.");
    set.insert("During your next turn, this Pokémon can't attack.");
    set.insert("Take a [R] Energy from your Energy Zone and attach it to this Pokémon.");
    set.insert("Your opponent's Active Pokémon is now Burned.");
    set.insert("Discard all [R] Energy from this Pokémon.");
    set.insert("Heal 20 damage from this Pokémon.");
    set.insert("This attack also does 30 damage to 1 of your opponent's Benched Pokémon.");
    set.insert("This attack also does 20 damage to 1 of your opponent's Benched Pokémon.");
    set.insert("If your opponent's Active Pokémon is a [F] Pokémon, this attack does 30 more damage.");
    set.insert("Discard 3 [W] Energy from this Pokémon. This attack also does 20 damage to each of your opponent's Benched Pokémon.");
    set.insert("Choose 2 of your Benched Pokémon. For each of those Pokémon, take a [W] Energy from your Energy Zone and attach it to that Pokémon.");
    set.insert("Discard a [L] Energy from this Pokémon.");
    set.insert("This Pokémon also does 10 damage to itself.");
    set.insert("Take a [L] Energy from your Energy Zone and attach it to this Pokémon.");
    set.insert("If this Pokémon has at least 2 extra [L] Energy attached, this attack does 80 more damage.");
    set.insert("Discard all [L] Energy from this Pokémon. This attack does 120 damage to 1 of your opponent's Pokémon.");
    set.insert("If this Pokémon has a Pokémon Tool attached, this attack does 40 more damage.");
    set.insert("If your opponent's Active Pokémon has a Pokémon Tool attached, this attack does 30 more damage.");
    set.insert("During your next turn, this Pokémon's Overdrive Smash attack does +60 damage.");
    set.insert("Take a [P] Energy from your Energy Zone and attach it to Mesprit or Azelf.");
    set.insert("You can use this attack only if you have Uxie and Azelf on your Bench. Discard all Energy from this Pokémon.");
    set.insert("This attack does 20 damage to 1 of your opponent's Pokémon.");
    set.insert("Discard the top 3 cards of your deck.");
    set.insert("Flip 2 coins. This attack does 20 more damage for each heads.");
    set.insert("If your opponent's Pokémon is Knocked Out by damage from this attack, this Pokémon also does 50 damage to itself.");
    set.insert("Flip 2 coins. This attack does 20 damage for each heads.");
    set.insert("If your opponent's Active Pokémon has damage on it, this attack does 40 more damage.");
    set.insert("This attack does 10 damage to each of your opponent's Pokémon.");
    set.insert("Flip 4 coins. This attack does 40 damage for each heads. If at least 2 of them are heads, your opponent's Active Pokémon is now Poisoned.");
    set.insert("Flip a coin for each Pokémon you have in play. This attack does 20 damage for each heads.");
    set.insert("Flip a coin for each Pokémon you have in play. This attack does 40 damage for each heads.");
    set.insert("If this Pokémon has a Pokémon Tool attached, this attack does 30 more damage.");
    set.insert("Flip a coin until you get tails. This attack does 30 more damage for each heads.");
    set.insert("Flip 3 coins. This attack does 50 more damage for each heads.");
    set.insert("Take 2 [M] Energy from your Energy Zone and attach it to 1 of your Benched Pokémon.");
    set.insert("Flip a coin until you get tails. This attack does 40 more damage for each heads.");
    set.insert("Flip a coin. If heads, this attack does 20 more damage.");
    set.insert("Change the type of the next Energy that will be generated for your opponent to 1 of the following at random: [G], [R], [W], [L], [P], [F], [D], or [M].");
    set.insert("Flip 2 coins. This attack does 40 damage for each heads.");
    set.insert("Before doing damage, discard all Pokémon Tools from your opponent's Active Pokémon.");
    set.insert("Halve your opponent's Active Pokémon's remaining HP, rounded down.");
    set.insert("Your opponent reveals their hand. Choose a card you find there and shuffle it into your opponent's deck.");
    set.insert("Flip 3 coins. This attack does 20 damage for each heads.");
    set.insert("Flip a coin. If heads, put your opponent's Active Pokémon into their hand.");
    set.insert("This attack does more damage equal to the damage this Pokémon has on it.");
    set.insert("Flip 2 coins. If both of them are heads, this attack does 70 more damage.");
    set.insert("This Pokémon also does 30 damage to itself.");
    set.insert("If this Pokémon has damage on it, this attack does 40 more damage.");
    set.insert("Flip a coin. If heads, this attack does 60 more damage. If tails, this Pokémon also does 20 damage to itself.");
    set.insert("This attack also does 10 damage to 1 of your opponent's Benched Pokémon.");
    set.insert("During your opponent's next turn, attacks used by the Defending Pokémon do -30 damage.");
    set.insert("Flip a coin. If heads, your opponent reveals a random card from their hand and shuffles it into their deck.");
    set.insert("This attack does 20 damage to 1 of your opponent's Benched Pokémon.");
    set.insert("If your opponent's Active Pokémon is a Pokémon ex, this attack does 30 more damage.");
    set.insert("During your next turn, this Pokémon's Rolling Spin attack does +60 damage.");
    set.insert("Your opponent's Active Pokémon is now Poisoned. Do 20 damage to this Pokémon instead of the usual amount for this Special Condition.");
    set.insert("If your opponent's Active Pokémon is a [M] Pokémon, this attack does 30 more damage.");
    set.insert("Flip a coin. If tails, during your next turn, this Pokémon can't attack.");
    set.insert("Discard 2 random Energy from this Pokémon.");
    set.insert("This Pokémon is now Asleep.");
    set.insert("This attack does 20 more damage for each of your Benched Pokémon.");
    set.insert("Put 1 random Weedle from your deck onto your Bench.");
    set.insert("If your opponent's Active Pokémon is a Pokémon ex, this attack does 70 more damage.");
    set.insert("Take 3 [R] Energy from your Energy Zone and attach it to this Pokémon.");
    set.insert("1 of your opponent's Pokémon is chosen at random. Do 30 damage to it.");
    set.insert("1 of your opponent's Pokémon is chosen at random 3 times. For each time a Pokémon was chosen, do 50 damage to it.");
    set.insert("Take a [L] Energy from your Energy Zone and attach it to 1 of your Benched [L] Pokémon.");
    set.insert("This attack also does 20 damage to each of your opponent's Benched Pokémon that has any Energy attached.");
    set.insert("Flip 4 coins. This attack does 20 damage for each heads.");
    set.insert("If this Pokémon has at least 2 extra [F] Energy attached, this attack does 50 more damage.");
    set.insert("If your opponent's Active Pokémon is Poisoned, this attack does 60 more damage.");
    set.insert("Flip a coin. If heads, your opponent's Active Pokémon is now Confused.");
    set.insert("Flip a coin. If heads, this attack does 80 more damage.");
    set.insert("Flip a coin for each [M] Energy attached to this Pokémon. This attack does 50 damage for each heads.");
    set.insert("During your next turn, this Pokémon's Overacceleration attack does +20 damage.");
    set.insert("This attack does 10 damage to 1 of your opponent's Pokémon.");
    set.insert("This attack does 100 damage to 1 of your opponent's Pokémon that have damage on them.");
    set.insert("This attack does 20 damage to each of your opponent's Pokémon.");
    set.insert("Flip 3 coins. This attack does 50 damage for each heads.");
    set.insert("If this Pokémon moved from your Bench to the Active Spot this turn, this attack does 60 more damage.");
    set.insert("Flip a coin. If tails, this Pokémon also does 20 damage to itself.");
    set.insert("Flip 2 coins. This attack does 70 damage for each heads. If at least 1 of them is heads, your opponent's Active Pokémon is now Burned.");
    set.insert("Discard a random Energy from both Active Pokémon.");
    set.insert("Your opponent's Active Pokémon is now Poisoned and Burned.");
    set.insert("During your opponent's next turn, if this Pokémon is damaged by an attack, do 40 damage to the Attacking Pokémon.");
    set.insert("Take a [W] Energy from your Energy Zone and attach it to this Pokémon.");
    set.insert("During your next turn, this Pokémon's Insatiable Striking attack does +40 damage.");
    set.insert("Put 1 random Wishiwashi or Wishiwashi ex from your deck onto your Bench.");
    set.insert("This attack does 40 more damage for each of your Benched Wishiwashi and Wishiwashi ex.");
    set.insert("If your opponent's Active Pokémon is a Basic Pokémon, this attack does 60 more damage.");
    set.insert("Discard 2 [L] Energy from this Pokémon.");
    set.insert("During your opponent's next turn, they can't play any Item cards from their hand.");
    set.insert("Switch this Pokémon with 1 of your Benched [L] Pokémon.");
    set.insert("Take a [P] Energy from your Energy Zone and attach it to this Pokémon.");
    set.insert("During your opponent's next turn, they can't take any Energy from their Energy Zone to attach to their Active Pokémon.");
    set.insert("This attack also does 20 damage to 1 of your Pokémon.");
    set.insert("This attack does 20 damage to 1 of your opponent's Pokémon for each Energy attached to that Pokémon.");
    set.insert("During your opponent's next turn, this Pokémon takes -50 damage from attacks.");
    set.insert("Put a random card that evolves from Rockruff from your deck into your hand.");
    set.insert("If your opponent's Active Pokémon has more remaining HP than this Pokémon, this attack does 50 more damage.");
    set.insert("This Pokémon also does 40 damage to itself.");
    set.insert("Discard a random Item card from your opponent's hand.");
    set.insert("1 Special Condition from among Asleep, Burned, Confused, Paralyzed, and Poisoned is chosen at random, and your opponent's Active Pokémon is now affected by that Special Condition. Any Special Conditions already affecting that Pokémon will not be chosen.");
    set.insert("If your opponent's Active Pokémon is affected by a Special Condition, this attack does 60 more damage.");
    set.insert("Flip a coin until you get tails. This attack does 70 damage for each heads.");
    set.insert("If your opponent's Active Pokémon has an Ability, this attack does 40 more damage.");
    set.insert("If any of your Benched Pokémon have damage on them, this attack does 50 more damage.");
    set.insert("During your opponent's next turn, this Pokémon takes +30 damage from attacks.");
    set.insert("Take a [C] Energy from your Energy Zone and attach it to 1 of your Benched Pokémon.");
    set.insert("If your opponent's Active Pokémon is a [D] Pokémon, this attack does 30 more damage.");
    set.insert("This Pokémon is now Confused.");
    set.insert("During your opponent's next turn, attacks used by the Defending Pokémon cost 1 [C] more, and its Retreat Cost is 1 [C] more.");
    set.insert("Flip 3 coins. This attack does 10 damage for each heads.");
    set.insert("This attack does 70 damage to 1 of your opponent's Pokémon.");
    set.insert("During your next turn, this Pokémon can't use Big Beat.");
    set.insert("This Pokémon also does 70 damage to itself.");
    set.insert("Discard a [F] Energy from this Pokémon.");
    set.insert("If Passimian is on your Bench, this attack does 40 more damage.");
    set.insert("Discard a random Pokémon Tool card from your opponent's hand.");
    set.insert("Flip 3 coins. For each heads, a card is chosen at random from your opponent's hand. Your opponent reveals that card and shuffles it into their deck.");
    set.insert("Flip a coin until you get tails. For each heads, discard a random Energy from your opponent's Active Pokémon.");
    set.insert("Flip 3 coins. This attack does 60 damage for each heads.");
    set.insert("Flip 2 coins. If both of them are heads, your opponent's Active Pokémon is Knocked Out.");
    set.insert("If you played a Supporter card from your hand during this turn, this attack does 50 more damage.");
    set.insert("This attack does 20 more damage for each [G] Energy attached to this Pokémon.");
    set.insert("Your opponent reveals a random card from their hand and shuffles it into their deck.");
    set.insert("If 1 of your Pokémon used Sweets Relay during your last turn, this attack does 30 more damage.");
    set.insert("Take a [R] Energy from your Energy Zone and attach it to 1 of your Benched Pokémon.");
    set.insert("If 1 of your Pokémon used Sweets Relay during your last turn, this attack does 20 more damage.");
    set.insert("If this Pokémon has at least 1 extra [W] Energy attached, this attack does 40 more damage.");
    set.insert("If this Pokémon evolved during this turn, this attack does 20 more damage.");
    set.insert("Discard all Energy attached to this Pokémon. Your opponent's Active Pokémon is now Paralyzed.");
    set.insert("This attack does 20 damage for each Energy attached to all of your opponent's Pokémon.");
    set.insert("If 1 of your Pokémon used Sweets Relay during your last turn, this attack does 60 more damage.");
    set.insert("This attack does 30 more damage for each Evolution Pokémon on your Bench.");
    set.insert("Flip a coin. If heads, choose 1 of your opponent's Active Pokémon's attacks and use it as this attack.");
    set.insert("This attack does 40 damage for each time your Pokémon used Sweets Relay during this game.");
    set.insert("This attack also does 10 damage to each of your Benched Pokémon.");
    set.insert("If the Defending Pokémon is a Basic Pokémon, it can't attack during your opponent's next turn.");
    set.insert("Discard all Pokémon Tools from your opponent's Active Pokémon.");
    set.insert("During your opponent's next turn, if this Pokémon is damaged by an attack, do 30 damage to the Attacking Pokémon.");
    set.insert("Flip a coin. If tails, this attack does nothing. If heads, your opponent's Active Pokémon is now Paralyzed.");
    set.insert("This attack does 20 damage for each of your Benched Pokémon.");
    set.insert("If this Pokémon has a Pokémon Tool attached, this attack does 50 more damage.");
    set.insert("Flip 3 coins. This attack does 60 damage for each heads. This Pokémon is now Confused.");
    set.insert("This attack does 40 more damage for each Energy in your opponent's Active Pokémon's Retreat Cost.");
    set.insert("If this Pokémon has no damage on it, this attack does 40 more damage.");
    set.insert("1 other Pokémon (either yours or your opponent's) is chosen at random 3 times. For each time a Pokémon was chosen, do 50 damage to it.");
    set.insert("Take a [R] Energy from your Energy Zone and attach it to 1 of your Benched Basic Pokémon.");
    set.insert("Flip a coin. If tails, discard 2 random Energy from this Pokémon.");
    set.insert("Take a [R], [W], and [L] Energy from your Energy Zone and attach them to your Benched Basic Pokémon in any way you like.");
    set.insert("If your opponent's Active Pokémon is Burned, this attack does 60 more damage.");
    set.insert("You may discard any number of your Benched [W] Pokémon. This attack does 40 more damage for each Benched Pokémon you discarded in this way.");
    set.insert("Put a random Pokémon from your deck into your hand.");
    set.insert("If the Defending Pokémon tries to use an attack, your opponent flips a coin. If tails, that attack doesn't happen. This effect lasts until the Defending Pokémon leaves the Active Spot, and it doesn't stack.");
    set.insert("Move all Energy from this Pokémon to 1 of your Benched Pokémon.");
    set.insert("Flip a coin. If heads, your opponent's Active Pokémon is now Paralyzed. If tails, your opponent's Active Pokémon is now Confused.");
    set.insert("Take a [L] Energy from your Energy Zone and attach it to 1 of your Benched Basic Pokémon.");
    set.insert("This attack also does 10 damage to 1 of your Benched Pokémon.");
    set.insert("This Pokémon is now Asleep. Heal 30 damage from it.");
    set.insert("This attack does 20 damage for each Energy attached to your opponent's Active Pokémon.");
    set.insert("Flip a coin. If heads, your opponent's Active Pokémon's remaining HP is now 10.");
    set.insert("If this Pokémon was damaged by an attack during your opponent's last turn while it was in the Active Spot, this attack does 50 more damage.");
    set.insert("Both Active Pokémon are now Asleep.");
    set.insert("This attack also does 20 damage to each of your Benched Pokémon.");
    set.insert("If this Pokémon has at least 2 extra [F] Energy attached, this attack does 60 more damage.");
    set.insert("Discard a random card from your opponent's hand.");
    set.insert("If this Pokémon moved from your Bench to the Active Spot this turn, this attack does 50 more damage.");
    set.insert("During your next turn, this Pokémon's Gear Spinner attack does +70 damage.");
    set.insert("If your opponent's Active Pokémon is a [G] Pokémon, this attack does 40 more damage.");
    set.insert("Flip a coin. If heads, during your opponent's next turn, prevent all damage done to this Pokémon by attacks.");
    set.insert("This attack does 20 more damage for each Energy attached to this Pokémon.");
    set.insert("If your opponent's Active Pokémon is an Evolution Pokémon, this attack does 40 more damage.");
    set.insert("During your opponent's next turn, attacks used by the Defending Pokémon cost 1 [C] more.");
    set.insert("Flip a coin. If tails, this attack does nothing. If heads, during your opponent's next turn, prevent all damage from—and effects of—attacks done to this Pokémon.");
    set.insert("Draw cards until you have the same number of cards in your hand as your opponent.");
    set.insert("Change the type of a random Energy attached to your opponent's Active Pokémon to 1 of the following at random: [G], [R], [W], [L], [P], [F], [D], or [M].");
    set.insert("Discard a [R], [W], and [L] Energy from this Pokémon.");
    set.insert("You may switch this Pokémon with 1 of your Benched Pokémon.");
    set.insert("If your opponent's Active Pokémon is an evolved Pokémon, devolve it by putting the highest Stage Evolution card on it into your opponent's hand.");
    set.insert("Discard the top card of your opponent's deck.");
    set.insert("If this Pokémon has at least 2 extra [R] Energy attached, this attack does 60 more damage.");
    set.insert("Put 1 random Poliwag from your deck onto your Bench.");
    set.insert("Flip a coin. If heads, your opponent's Active Pokémon is now Poisoned and Paralyzed.");
    set.insert("Discard up to 2 Pokémon Tool cards from your hand. This attack does 50 damage for each card you discarded in this way.");
    set.insert("This attack does 20 damage for each Benched Pokémon (both yours and your opponent's).");
    set.insert("Take a [W] Energy from your Energy Zone and attach it to 1 of your Benched Basic Pokémon.");
    set.insert("If this Pokémon has damage on it, this attack can be used for 1 [L] Energy.");
    set.insert("At the end of your opponent's next turn, do 90 damage to the Defending Pokémon.");
    set.insert("If Latios is on your Bench, this attack does 20 more damage.");
    set.insert("Discard the top card of your deck. If that card is a [F] Pokémon, this attack does 60 more damage.");
    set.insert("If this Pokémon has any [W] Energy attached, this attack does 40 more damage.");
    set.insert("This attack does damage to your opponent's Active Pokémon equal to the damage this Pokémon has on it.");
    set.insert("If your opponent's Active Pokémon is Zangoose, this attack does 40 more damage.");
    set.insert("If this Pokémon has 2 or more different types of Energy attached, this attack does 60 more damage.");
    set.insert("This attack does 60 damage to 1 of your opponent's Pokémon.");
    set.insert("Until this Pokémon leaves the Active Spot, this Pokémon's Rolling Frenzy attack does +30 damage. This effect stacks.");
    set.insert("Heal 50 damage from 1 of your Benched Pokémon.");
    set.insert("Flip a coin. If heads, this attack does 70 more damage.");
    set.insert("During your opponent's next turn, prevent all damage done to this Pokémon by attacks if that damage is 40 or less.");
    set.insert("Choose either Poisoned or Confused. Your opponent's Active Pokémon is now affected by that Special Condition.");
    set.insert("Flip 3 coins. This attack does 40 damage for each heads.");
    set.insert("This attack does 30 more damage for each Energy in your opponent's Active Pokémon's Retreat Cost.");
    set.insert("During your next turn, this Pokémon can't use Sacred Sword.");
    set.insert("Flip a coin. If heads, your opponent's Active Pokémon is now Burned.");
    set.insert("Heal 30 damage from each of your Benched Basic Pokémon.");
    set.insert("Discard Fire[R] Energy from this Pokémon. Your opponent's Active Pokémon is now Burned.");
    set.insert("Flip 2 coins. This attack does 30 more damage for each heads.");
    set.insert("During your opponent's next turn, if this Pokémon is damaged by an attack, do 20 damage to the Attacking Pokémon.");
    set.insert("Put a random card from your deck that evolves from this Pokémon onto this Pokémon to evolve it.");
    set.insert("Discard the top 3 cards of your opponent's deck.");
    set.insert("If you have exactly 1, 3, or 5 cards in your hand, this attack does 60 more damage.");
    set.insert("This attack does 10 more damage for each [W] Energy attached to this Pokémon.");
    set.insert("If you have exactly 2, 4, or 6 cards in your hand, this attack does 30 more damage.");
    set.insert("Prevent all damage done to this Pokémon by attacks from Basic Pokémon during your opponent's next turn.");
    set.insert("1 of your opponent's Benched Pokémon is chosen at random. This attack also does 20 damage to it.");
    set.insert("1 of your opponent's Benched Pokémon is chosen at random 3 times. For each time a Pokémon was chosen, also do 20 damage to it.");
    set.insert("This attack also does 20 damage to 1 of your Benched Pokémon.");
    set.insert("If your opponent's Active Pokémon has damage on it, this attack does 30 more damage.");
    set.insert("Discard a [L] Energy from your opponent's Active Pokémon.");
    set.insert("Discard a card from your hand. If you can't, this attack does nothing.");
    set.insert("This attack does 30 more damage for each of your Benched Pokémon.");
    set.insert("Discard 2 cards from your hand. If you can't discard 2 cards, this attack does nothing.");
    set.insert("During your opponent's next turn, if they attach Energy from their Energy Zone to the Defending Pokémon, that Pokémon will be Asleep.");
    set.insert("This attack's damage isn't affected by Weakness.");
    set.insert("If this Pokémon has damage on it, this attack does 50 more damage.");
    set.insert("This attack does 20 damage to each of your opponent's Pokémon. During your next turn, this Pokémon's Wild Spin attack does +20 damage to each of your opponent's Pokémon.");
    set.insert("Reveal the top 3 cards of your deck. This attack does 60 damage for each Pokémon with a Retreat Cost of 3 or more you find there. Shuffle the revealed cards back into your deck.");
    set.insert("If this Pokémon's remaining HP is 30 or less, this attack does 60 more damage.");
    set.insert("If your opponent's Active Pokémon is a [G] Pokémon, this attack does 50 more damage.");
    set.insert("This attack does 40 more damage for each of your opponent's Pokémon in play that has an Ability.");
    set.insert("Flip a coin. If heads, your opponent reveals their hand. Choose a Supporter card you find there and discard it.");
    set.insert("Your opponent reveals their hand. Choose a Supporter card you find there and discard it.");
    set.insert("During your next turn, this Pokémon's Overdrive Smash attack does +30 damage.");
    set.insert("If your opponent's Active Pokémon is Poisoned, this attack does 70 more damage.");
    set.insert("This attack's damage isn't affected by any effects on your opponent's Active Pokémon.");
    set.insert("If Durant is on your Bench, this attack does 40 more damage.");
    set.insert("Discard 2 [M] Energy from this Pokémon. During your opponent's next turn, this Pokémon takes -50 damage from attacks.");
    set.insert("Flip 2 coins. If both of them are tails, this attack does nothing.");
    set.insert("Heal 40 damage from this Pokémon.");
    set.insert("Flip 2 coins. For each heads, discard a random Energy from your opponent's Active Pokémon. If both of them are tails, this attack does nothing.");
    set.insert("Flip a coin. If tails, this Pokémon also does 30 damage to itself.");
    set.insert("Flip 2 coins. This attack does 30 damage for each heads. If this Pokémon has Lucky Mittens attached, flip 4 coins instead.");
    set.insert("Both Active Pokémon are now Confused.");
    set.insert("If your opponent's Active Pokémon is a Basic Pokémon, this attack does 70 more damage.");
    set.insert("Flip a coin until you get tails. This attack does 40 damage for each heads.");
    set.insert("1 of your opponent's Pokémon is chosen at random 4 times. For each time a Pokémon was chosen, do 40 damage to it.");
    set.insert("Discard a [M] Energy from this Pokémon.");
    set.insert("Discard the top 5 cards of each player's deck.");
    set.insert("Flip a coin. If heads, switch in 1 of your opponent's Benched Pokémon to the Active Spot.");
    set.insert("Flip a coin. If heads, heal 60 damage from this Pokémon.");
    set
});

/// Get the implementation for a given attack effect text.
/// Returns None if the effect is not yet implemented.
/// All effects currently return None - implementations to be added later.
pub fn get_effect_implementation(effect_text: &str) -> AttackEffect {
    if KNOWN_EFFECTS.contains(effect_text) {
        None // TODO: Return actual implementation
    } else {
        None
    }
}
